name: Compatibility builds

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

jobs:
  compatibility:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['3.2.12', '3.4.0-SNAPSHOT']

    name: Compatibility with Spring Boot ${{ matrix.version }}

    steps:

    - name: Check out sources
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build
      run: ./mvnw -B verify -Dspring-boot.version=${{ matrix.version }} --file pom.xml
